# Introduction to Numpy and Pandas

© Explore Data Science Academy

## Learning Objectives
By the end of this train, you should be able to:
* Perform basic operations in Numpy;
* Perform basic operations in Pandas; and
* Analyse data using Numpy and Pandas.

## Outline
In this train we will:
* Introduce the Numpy Python library and some of its functionality;
* Introduce the Pandas Python and some of its functionality; and
* Load, manipulate, and analyse data using Numpy and Pandas.

## Introduction

Python has many packages for working with data and performing operations like the loading, analysing and storing of data. Numpy and Pandas are two commonly used and useful ones. In this train, you will learn some of the basic operations in Numpy and Pandas.

# Numpy
Numpy is a Python package which provides high-performance, multidimensional array objects, numerical computing tools, and is fundamental in scientific computing. It is the core library for scientific computing in Python ([see the full documentation](https://numpy.org/)). We will start by defining what an array is, how to create an array, how to access and modify an array, and look at useful functions on arrays. Finally, we will identify when an array should be the chosen data structure when performing data analysis or manipulation.

### What is an Array?
Similar to that of a Python list, a numpy array is a data structure which stores multiple values. The main difference between the two is that lists can contain heterogeneous data types (combinations of `str`, `int`, even `list`), whilst numpy arrays can only store values of the same data type. Numpy arrays can be thought of as a grid of values and can be multi-dimensional.

Numpy arrays are stored more efficiently than Python lists and allow mathematical operations to be vectorized, which results in significantly higher performance than with looping constructs in Python.

### Creating a Numpy Array
If we want to work with any numpy objects or functions we first need to import the Numpy library.


In [1]:
import numpy as np

To make a numpy array, you use the `np.array()` function. All you need to do is pass a list to it and optionally, you can specify the data type of the data. Let's look at an example:

In [2]:
# Create an array by passing in a list of lists.
ratings = np.array([[94,89,63], [93,92,48], [92,94,56]])

ratings

array([[94, 89, 63],
       [93, 92, 48],
       [92, 94, 56]])

You can see that there are 3 rows and columns in this array. We can inspect the shape of the array by using its `shape` attribute. This will return a tuple of integers giving the size of the array along each dimension.

In [3]:
ratings.shape

(3, 3)

We can also create arrays using the following functions:

* `np.ones()` - array of ones
* `np.zeros()` - array of zeros
* `np.random.random()` - array with random values

Let's look at some examples:

In [4]:
# Create an array of ones - pass in shape as a tuple.
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
# Create an array of zeros - pass in shape as a tuple.
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# Create an array of random values - pass in shape as a tuple.
np.random.random((3,3))

array([[0.88427834, 0.81591151, 0.91464321],
       [0.78496124, 0.60602797, 0.08391617],
       [0.98623361, 0.98582064, 0.53959781]])

### Accessing Numpy Arrays
Numpy offers several ways to index into arrays. Here, we'll work through slicing, and Boolean array indexing.

#### Slicing
Similar to Python lists, Numpy arrays can be sliced. Since arrays may be multi-dimensional, you must specify a slice for each dimension of the array, where the slices per dimension is split by a comma. For a 2-D array, the first dimension is the vertical axis while the second dimension is the horizontal axis. For a 2-D array:

* `np.array[vertical index , horizontal index]` - for one element
* `np.array[vertical start:vertical end , horizontal start:horizontal end]` - for more than one element 

Let's look at a few examples:

In [7]:
# Whole array.
ratings

array([[94, 89, 63],
       [93, 92, 48],
       [92, 94, 56]])

In [8]:
# Select top left element.
ratings[0,0]

94

In [9]:
# Select first row.
ratings[0,:]

array([94, 89, 63])

In [10]:
# Select first column.
ratings[:,0]

array([94, 93, 92])

In [11]:
# Select first two rows and first two columns.
ratings[0:2,0:2]

array([[94, 89],
       [93, 92]])

#### Boolean Array Indexing
Boolean array indexing let's you pick out a selection of elements from an array. This type of indexing is often used to select the elements of an array which satisfy a specific condition. The syntax is as follows:

* `np.array[condition]`

Let's look at an example:

In [12]:
# Select all values greater than 90.
ratings[ratings > 90]

array([94, 93, 92, 92, 94])

### Modifying Numpy Arrays
We will now look at how to add elements to an array, followed by how to remove elements from an array.

#### Adding Elements
Adding elements can be done by using the `np.append()` function. This will add elements to the end of an array. Let's look at an example:

In [13]:
# Append an extra row - note that axis=0.
ratings_extra_row = np.append(ratings, [[92, 88, 78]], axis=0)

ratings_extra_row

array([[94, 89, 63],
       [93, 92, 48],
       [92, 94, 56],
       [92, 88, 78]])

#### Removing Elements
Deleting elements can be done by using the `np.delete()` function. This will delete elements at the specified indices. Let's look at an example:

In [14]:
# Delete the 3rd row - note that axis=0.
ratings_del_row = np.delete(ratings, [2], axis=0)

ratings_del_row

array([[94, 89, 63],
       [93, 92, 48]])

### Functions on Numpy Arrays
There are various functions we can perform on numpy arrays. We will look at a few of them, namely:

* `np.array.sum()`
* `np.array.min()`
* `np.array.max()`

In all these functions we can pass an axis argument. This will allow us to sum the columns and rows separately. Let's look at examples:

In [15]:
# Sum of all elements in array.
ratings.sum()

721

In [16]:
# Sum of each row.
ratings.sum(axis=1)

array([246, 233, 242])

In [17]:
# Min of each row.
ratings.min(axis=1)

array([63, 48, 56])

In [18]:
# Max of each column.
ratings.max(axis=0)

array([94, 94, 63])

### When to use Numpy Arrays

A Numpy array is a data structure which stores multiple values, all of the same data type, and can be multi-dimensional. We should use a Numpy array if all of the following statements hold:

* We have multi-dimensional data
* All entries are of the same data type

Numpy arrays are also preferred over list of lists due to efficiency and functionality.

## Pandas

In this section we will look at Pandas dataframes, which is most commonly used for any Python data analysis. We will define what a Pandas dataframe is, show how to create dataframes and how to access them. 

### What is a Pandas Dataframe?
Pandas is a data manipulation tool which is built on the Numpy package. Pandas' key data structure is the `dataframe`. A dataframe allows for the storage and manipulation of tabular data. It is a two-dimensional labelled data structure. 

<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/Pandas_dataframe.jpg">

Basically, you could say that the Pandas dataframe consists of three main components: the data, index, and columns. Let's walk through some examples to gain an understanding of these components.

#### Creating a Dataframe
We can create a dataframe by calling the `DataFrame()` constructor. The main arguments in the constructor are the data, index and columns. The data that is passed in can be in the form of other data structures (lists, dictionaries or numpy arrays) or by loading in a file.

Let's start our examples by first importing the Pandas library:

In [20]:
import pandas as pd

#### Dataframes from other Data Structures

We now look at some examples on how to create a dataframe from various data structures in Python. 

Using **lists**, we need to create a list of lists (nested list) with the relevant data. We then also need to pass an index (player names in this example) and column names.

In [21]:
# Create list of lists containing data.
list_df = [[32, 'Portugal', 94], [30, 'Argentina', 93], [25 , 'Brazil', 92]]

# Create index - names of players.
index = ['Christiano Ronaldo', 'Lionel Messi', 'Neymar']

# Create column names.
columns = ['Age', 'Nationality', 'Overall']

# Create dataframe by passing in data, index and columns.
pd.DataFrame(data=list_df, index=index, columns=columns)

Age Nationality  Overall
Christiano Ronaldo   32    Portugal       94
Lionel Messi         30   Argentina       93
Neymar               25      Brazil       92

Using **dictionaries**, we need to create a dictionary with the relevant data. 

The keys should be the column names, while the values should be the data entries for that column. We then also need to pass an index. Note that because the keys account for the column names, we don't have to pass in an argument for columns.

In [22]:
# Create dictionary containing data.
dict_df = {'Age':[32, 30, 25], 'Nationality':['Portugal', 'Argentina', 'Brazil'], 'Overall':[94, 93, 92]}

# Create index - names of players.
index = ['Christiano Ronaldo', 'Lionel Messi', 'Neymar']

# Create dataframe by passing in data, index and columns.
pd.DataFrame(data=dict_df, index=index)

Age Nationality  Overall
Christiano Ronaldo   32    Portugal       94
Lionel Messi         30   Argentina       93
Neymar               25      Brazil       92

Using **numpy arrays**, we need to create a numpy array with the relevant data. We then also need to pass an index (player names) and column names.

In [23]:
# Create numpy array containing data.
array_df = np.array([[32, 'Portugal', 94], [30, 'Argentina', 93], [25 , 'Brazil', 92]])

# Create index - names of players.
index = ['Christiano Ronaldo', 'Lionel Messi', 'Neymar']

# Create column names.
columns = ['Age', 'Nationality', 'Overall']

# Create dataframe by passing in data, index and columns.
pd.DataFrame(data=array_df, index=index, columns=columns)

Age Nationality Overall
Christiano Ronaldo  32    Portugal      94
Lionel Messi        30   Argentina      93
Neymar              25      Brazil      92

#### Dataframes from other files
The data argument can also be a loaded file. We will load the full csv file. Pandas make it very easy to do this; you simply load the data using the `read_csv()` function and pass in the full path of the file as a string.

Pandas will use the first row as columns so we don't need to pass column names. We can also specify the index when we load the data by passing our index column as a string under the index_col argument.

In [26]:
# Load data - pass 'Name' as our index column.
# For this exercise, we'll use football player data to evaluate our dataframe.
load_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/fundamentals/football_players.csv', index_col='Name')

# Create dataframe called df.
df = pd.DataFrame(load_df)

# Use the head() function to look at the first 5 rows.
df.head()

Age Nationality  Overall Acceleration Aggression Agility  \
Name                                                                          
Cristiano Ronaldo   32    Portugal       94       89         63      89       
L. Messi            30   Argentina       93       92         48      90       
Neymar              25      Brazil       92       94         56      96       
L. Suárez           30     Uruguay       92       88         78      86       
M. Neuer            31     Germany       92       58         29      52       

                  Balance Ball control Composure Crossing  ... Short passing  \
Name                                                       ...                 
Cristiano Ronaldo  63           93        95       85      ...        83       
L. Messi           95           95        96       77      ...        88       
Neymar             82           95        92       75      ...        81       
L. Suárez          60           91        83       77      ...        83       
M. Neuer           35           48        70       15      ...        55       

                  Shot power Sliding tackle Sprint speed Stamina  \
Name                                                               
Cristiano Ronaldo     94             23           91      92       
L. Messi              85             26           87      73       
Neymar                80             33           90      78       
L. Suárez             87             38           77      89       
M. Neuer              25             11           61      44       

                  Standing tackle Strength  Vision Volleys Preferred Positions  
Name                                                                            
Cristiano Ronaldo          31       80      85      88                  ST LW   
L. Messi                   28       59      90      85                     RW   
Neymar                     24       53      80      83                     LW   
L. Suárez                  45       80      84      88                     ST   
M. Neuer                   10       83      70      11                     GK   

[5 rows x 38 columns]

We use the `head()` function to only look at the first 5 records of our data. This is helpful if the dataframe has many rows and loading it will take lots of time.

### Accessing Dataframes

Accessing data within dataframes is not as straightforward as with the previous data structures. This can be done by index, by column, or by both. Let's work through these methods.

#### By Index
To access by index only in a dataframe we can use the `iloc` or `loc` functions with the indices in square brackets. The `iloc` function refers to the index location, so we pass in the number of the index, while the `loc` function refers to the name of the index, so we pass in the index name. Use slicing if you want more than one index. Eg:

* `dataframe.iloc[index i]` - returns series at index i
* `dataframe.iloc[index start: index end]` - returns dataframe from start to end (end not included)
* `dataframe.loc['index name']` - returns series of given index name

Let's look at a few examples:

In [27]:
# Select the 5th row using iloc[].
df.iloc[4]

Age                         31
Nationality            Germany
Overall                     92
Acceleration            58    
Aggression              29    
Agility                 52    
Balance                 35    
Ball control            48    
Composure               70    
Crossing                15    
Curve                   14    
Dribbling               30    
Finishing               13    
Free kick accuracy      11    
GK diving               91    
GK handling             90    
GK kicking              95    
GK positioning          91    
GK reflexes             89    
Heading accuracy        25    
Interceptions           30    
Jumping                 78    
Long passing            59    
Long shots              16    
Marking                 10    
Penalties               47    
Positioning             12    
Reactions               85    
Short passing           55    
Shot power              25    
Sliding tackle          11    
Sprint speed            61    
Stamina 

In [28]:
# Select rows 5 to 10.
df.iloc[4:10]

Age Nationality  Overall Acceleration Aggression Agility  \
Name                                                                       
M. Neuer         31     Germany       92       58         29      52       
R. Lewandowski   28      Poland       91       79         80      78       
De Gea           26       Spain       90       57         38      60       
E. Hazard        26     Belgium       90       93         54      93       
T. Kroos         27     Germany       90       60         60      71       
G. Higuaín       29   Argentina       90       78         50      75       

               Balance Ball control Composure Crossing  ... Short passing  \
Name                                                    ...                 
M. Neuer        35           48        70       15      ...        55       
R. Lewandowski  80           89        87       62      ...        83       
De Gea          43           42        64       17      ...        50       
E. Hazard       91           92        87       80      ...        86       
T. Kroos        69           89        85       85      ...        90       
G. Higuaín      69           85        86       68      ...        75       

               Shot power Sliding tackle Sprint speed Stamina Standing tackle  \
Name                                                                            
M. Neuer           25             11           61      44              10       
R. Lewandowski     88             19           83      79              42       
De Gea             31             13           58      40              21       
E. Hazard          79             22           87      79              27       
T. Kroos           87             69           52      77              82       
G. Higuaín         88             18           80      72              22       

               Strength  Vision Volleys Preferred Positions  
Name                                                         
M. Neuer         83      70      11                     GK   
R. Lewandowski   84      78      87                     ST   
De Gea           64      68      13                     GK   
E. Hazard        65      86      79                     LW   
T. Kroos         74      88      82                 CDM CM   
G. Higuaín       85      70      88                     ST   

[6 rows x 38 columns]

In [29]:
# Select the M. Neuer index using loc[].
df.loc['M. Neuer']

Age                         31
Nationality            Germany
Overall                     92
Acceleration            58    
Aggression              29    
Agility                 52    
Balance                 35    
Ball control            48    
Composure               70    
Crossing                15    
Curve                   14    
Dribbling               30    
Finishing               13    
Free kick accuracy      11    
GK diving               91    
GK handling             90    
GK kicking              95    
GK positioning          91    
GK reflexes             89    
Heading accuracy        25    
Interceptions           30    
Jumping                 78    
Long passing            59    
Long shots              16    
Marking                 10    
Penalties               47    
Positioning             12    
Reactions               85    
Short passing           55    
Shot power              25    
Sliding tackle          11    
Sprint speed            61    
Stamina 

#### By Column
To access by column only we can simply call `dataframe['Column Name']`. If we want more than one column we input a list of column names inside the square brackets:

* `dataframe['Column Name']` - returns series of given column
* `dataframe[['Column 1', 'Column 2']]` - returns dataframe with the given columns

Let's look at examples.

In [30]:
# Select the column 'Age'.
df['Age']

Name
Cristiano Ronaldo    32
L. Messi             30
Neymar               25
L. Suárez            30
M. Neuer             31
                     ..
A. Kelsey            17
B. Richardson        47
J. Young             17
J. Lundstram         18
L. Sackey            18
Name: Age, Length: 17981, dtype: int64

In [31]:
# Select the columns 'Age' and 'Nationality'.
df[['Age', 'Nationality']]

Age Nationality
Name                              
Cristiano Ronaldo   32    Portugal
L. Messi            30   Argentina
Neymar              25      Brazil
L. Suárez           30     Uruguay
M. Neuer            31     Germany
...                ...         ...
A. Kelsey           17     England
B. Richardson       47     England
J. Young            17    Scotland
J. Lundstram        18     England
L. Sackey           18       Ghana

[17981 rows x 2 columns]

#### By index and column
We can also select a subset of the dataframe using indices and columns in combination. Let's look at a few examples:

In [32]:
# Select the first 5 rows and first 2 columns - Rows first.
df.iloc[0:5][['Age', 'Nationality']]

Age Nationality
Name                              
Cristiano Ronaldo   32    Portugal
L. Messi            30   Argentina
Neymar              25      Brazil
L. Suárez           30     Uruguay
M. Neuer            31     Germany

In [33]:
# Select the first 5 rows and first 2 columns - Columns first.
df[['Age', 'Nationality']].iloc[0:5]

Age Nationality
Name                              
Cristiano Ronaldo   32    Portugal
L. Messi            30   Argentina
Neymar              25      Brazil
L. Suárez           30     Uruguay
M. Neuer            31     Germany

### When to use Dataframes
Unlike the Numpy array which is suited for storing and performing computations on homogeneous data (data of the same type), Pandas dataframes can accommodate heterogeneous data. This makes them the choice data structure for manipulating often messy data (e.g tabular data from spreadsheets, or SQL tables). 

We should use a Pandas dataframe if all of the following statements hold:

* We have 2-dimensional data (rows and columns)
* The data type is the same within a column
* We are interested in the index (rows) and column names

## Exercises

Here are some exercises for you to try out. The solutions can be found at the end of this train.

#### Exercise 1:
Select rows 9-14 of the football player dataframe we've just been using.

In [34]:
# Answer here

#### Exercise 2:
Select, in order, only the "Preferred Positions", "Overall" and "Age" columns for the football player Neymar.

In [35]:
# Answer here

#### Exercise 3:
Select, in order, only the "Overall", "Age" and "Nationality" columns for all players with ages of 35 years or older

In [36]:
# Answer here

## Conclusion
In this train, you learned to perform basic operations using more Numpy and Pandas, you also learnt how to load, manipulate and analyse data using these packages. The reader is expected to complete the exercises before moving forward to ensure familiarity with these packages.

## Solutions

In [37]:
# Exercise 1 solution

df.iloc[8:14]

Age Nationality  Overall Acceleration Aggression Agility  \
Name                                                                     
T. Kroos       27     Germany       90       60         60      71       
G. Higuaín     29   Argentina       90       78         50      75       
Sergio Ramos   31       Spain       90       75         84      79       
K. De Bruyne   26     Belgium       89       76         68      80       
T. Courtois    25     Belgium       89       46         23      61       
A. Sánchez     28       Chile       89       88         80      90       

             Balance Ball control Composure Crossing  ... Short passing  \
Name                                                  ...                 
T. Kroos      69           89        85       85      ...        90       
G. Higuaín    69           85        86       68      ...        75       
Sergio Ramos  60           84        80       66      ...        78       
K. De Bruyne  75           87        84       90      ...        90       
T. Courtois   45           23        52       14      ...        32       
A. Sánchez    87           87        86       80      ...        81       

             Shot power Sliding tackle Sprint speed Stamina Standing tackle  \
Name                                                                          
T. Kroos         87             69           52      77              82       
G. Higuaín       88             18           80      72              22       
Sergio Ramos     79             91           77      84              89       
K. De Bruyne     85             40           75      87              51       
T. Courtois      36             16           52      38              18       
A. Sánchez       84             35           84      85              39       

             Strength  Vision Volleys Preferred Positions  
Name                                                       
T. Kroos       74      88      82                 CDM CM   
G. Higuaín     85      70      88                     ST   
Sergio Ramos   81      63      66                     CB   
K. De Bruyne   73      90      82              RM CM CAM   
T. Courtois    70      44      12                     GK   
A. Sánchez     72      83      83            RM LW ST LM   

[6 rows x 38 columns]

In [38]:
# Exercise 2 solution

df.iloc[2][['Preferred Positions', 'Overall', 'Age']]

Preferred Positions    LW 
Overall                 92
Age                     25
Name: Neymar, dtype: object

In [39]:
# Exercise 3 solution

df[['Overall', 'Age', 'Nationality']][df['Age'] >= 35]

Overall  Age     Nationality
Name                                        
G. Buffon            89   39           Italy
Z. Ibrahimović       88   35          Sweden
P. Čech              86   35  Czech Republic
A. Barzagli          85   36           Italy
Aduriz               84   36           Spain
...                 ...  ...             ...
R. Kawai             52   38           Japan
Y. Nishibe           52   36           Japan
A. Al Basisi         52   39    Saudi Arabia
P. Jennings          52   37         England
B. Richardson        46   47         England

[468 rows x 3 columns]

## Appendix
- [Basic Numpy Functionality](https://numpy.org/doc/stable/user/absolute_beginners.html#what-is-an-array)

- [Numpy package home page](https://numpy.org)

- [Pandas package home page](https://pandas.pydata.org/)